[tool.commitizen]
version = "6.3.3"
version_files = [
    "Cargo.toml",
    "core/Cargo.toml",
    "adapters/proc/Cargo.toml",
    "ports/cli/Cargo.toml",
]
name = "cz_conventional_commits"
tag_format = "v$version"
bump_message = "bump: $current_version â†’ $new_version [skip-ci]"
